spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbc73ff7583e274711ac47dd441745ea40course
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
springdoc:
  swagger:
    enabled: true