spring:
  datasource:
    url: jdbc:h2:~/study
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  h2:
    console:
      path: /h2-console
      enabled: true
## 访问方式 {ip}:{port}//h2-console
springdoc:
  swagger:
    enabled: true